Create README-AR.md
freeCodeCamp/how-to-contribute-to-open-source pull request #457
Opened 2020-10-11 12:52 UTC by MohamdAlhawi

2020-10-11 13:44 UTC, carlosdeque-s commented
Well done

2020-10-13 17:10 UTC, MohamdAlhawi commented
> Issue link back #386

I do some translation every day as you see

2020-10-22 00:11 UTC, Elhadiq requested changes

2020-10-22 00:11 UTC, Elhadiq commented on README-AR.md
> +# أهلا بالمساهمين المبتدئين في البيئة مفتوحة المصدر
An open source project is not always an environment 
> # أهلا بالمساهمين المبتدئين في البيئة مفتوحة المصدر
What do you think about:
 مرحبا بالمساهمين الجدد في المصدر المفتوح

2020-10-22 00:36 UTC, Elhadiq requested changes

2020-10-22 00:36 UTC, Elhadiq commented on README-AR.md
> +قائمة المصادر الخاصة بالاشخاص الجدد في المساهمة في البيئة مفتوحة المصدر
Its a list of resources offred to the newbie in open source and not related to them
هي قائمة مقدمة للأشخاص الجدد وليست خاصة بهم
ثانيا نكرة ولست معرفى
a list of not the list of 
what i suggest :
 تجدون هنا قائمة مصادر في المصدر المفتوح للمساهمين الجدد

2020-10-22 00:36 UTC, Elhadiq commented on README-AR.md
> +**المحتويات**
Good job

2020-10-22 00:36 UTC, Elhadiq commented on README-AR.md
> +- [المساهمة في البيئة مفتوحة المصدر عامة](#contributing-to-open-source-in-general)
المساهمة في المصدر المفتوح بصفة عامة

2020-10-22 00:36 UTC, Elhadiq commented on README-AR.md
> +- [مقالات مفيدة للمساهيمن الجدد في بيئة مفتوحة المصدر](#useful-articles-for-new-open-source-contributors)
مقالات مفيدة للمساهيمن الجدد في المصدر المفتوح

2020-10-22 00:36 UTC, Elhadiq commented on README-AR.md
> +- [استخدام المتحكم في الإصدارات](#using-version-control)
كيفية استعمال مدير النسخ

2020-10-22 00:36 UTC, Elhadiq commented on README-AR.md
> +- [كتب للبيئة مفتوحة المقدر](#open-source-books)
> كتب للبيئة مفتوحة المقدر

 مجموعة كتب في المصدر المفتوح

2020-10-22 00:36 UTC, Elhadiq commented on README-AR.md
> +- [المبادرة للمساهمة في بيئة مفتوحة المصدر](#open-source-contribution-initiatives)
مبادرات للمساهمة في المصدر المفتوح

2020-10-22 06:13 UTC, MohamdAlhawi commented on README-AR.md
> +- [المبادرة للمساهمة في بيئة مفتوحة المصدر](#open-source-contribution-initiatives)
> مبادرات للمساهمة في المصدر المفتوح

بإمكانك إضافة التعديلات اللازمة مباشرة و مشكور مسبقاً

2020-10-22 17:45 UTC, Elhadiq commented on README-AR.md
> +- [المبادرة للمساهمة في بيئة مفتوحة المصدر](#open-source-contribution-initiatives)
شكرا لك

2021-01-02 18:04 UTC, khali70 commented
I'm free and happy to help

2021-01-02 18:22 UTC, MohamdAlhawi commented
> I'm free and happy to help

I'm happy to hear that, you can continue working

2021-01-06 21:59 UTC, alivx approved these changes

2021-01-09 19:12 UTC, khali70 commented on README-AR.md
> +## Open Source contribution initiatives
مبادرات للمشاركه في البيئه مفتوحه المصدر

2021-03-23 19:49 UTC, H1rkul2 reviewed
the translation until the last 3 sections is good

2022-01-14 12:54 UTC, ibrahimgb approved these changes

2022-02-05 20:24 UTC, Green-Abe approved these changes

2022-04-06 20:49 UTC, erictleung commented
Closing in favor of https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/670 Happy coding!

2022-04-06 20:49 UTC, closed without merging