Updated README.md with Adding new resources.
freeCodeCamp/how-to-contribute-to-open-source pull request #458
Opened 2020-10-12 03:37 UTC by jakaya123

I have included links to free ebooks that are super useful to open source contributors.

2020-10-12 09:27 UTC, raisedadead reviewed
Thanks for the PR.

I think while this could be useful. I think we should avoid adding resources which are not the direct authors/publishers of a book to avoid having to do the diligence on copyright etc.

The linked resource maybe following this, but the last thing we want it to be promoting it without diligence?

2020-10-14 04:36 UTC, erictleung requested changes
Thanks for the changes. See comments for some feedback.

2020-10-14 04:36 UTC, erictleung commented on README.md
> +- [Pro Git (Second Edition)](https://www.freetechbooks.com/pro-git-second-edition-t1202.html) - A fully-updated guide to Git and its usage in the modern world. This book teaches readers how to master
This book is already freely available in the previous section on Using Version Control https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README.md#L117

```suggestion
```

So we can just remove this.

2020-10-14 04:36 UTC, erictleung commented on README.md
> +- [The Architecture of Open Source Applications, Volume II: Structure, Scale, and a Few More Fearless Hacks](https://www.freetechbooks.com/the-architecture-of-open-source-applications-volume-ii-struc
Part of this is already in our list, but shown as just the git tool. We can update this link to point to all the books that are already freely available.

```suggestion
- [The Architecture of Open Source Applications](https://www.aosabook.org/en/index.html) - The authors of twenty-four open source applications explain how their software is structured, and why. From web servers and compilers to health record management systems, they are covered here to help you become a better developer.
```

2022-07-25 04:57 UTC, erictleung approved these changes
LGTM! 👍

2022-07-25 04:57 UTC, merged