Creating README-PL.md
freeCodeCamp/how-to-contribute-to-open-source pull request #460
Opened 2020-10-13 10:20 UTC by Kubaaa96

Translates README to Polish. 
Added few tutorials and books in Polish. I'm not sure if ,,kontrybutor'' is best translator for contributor. But in my opinion its better than ,,współautor'' Because of the similarities between Polish and English words i think its helpful in case someone learning English or trying to understand this language better. 

Also i have a little question about `bugs filed` in 
`a site dedicated to bugs filed for the developer tools in the Firefox browser.` Line 84 in main Readme. 
I'm not very familiar with http://firefox-dev.tools/ but am i right that it is used for finding bugs in apps related to Firefox browser or in browser itself?

2020-10-13 11:51 UTC, Ieahleen commented
thank you for your contribution, but now the translation is no more dealt with through GitHub, see here: https://contribute.freecodecamp.org/

2020-10-13 11:54 UTC, Ieahleen commented
wait, sorry, for this repo I don't actually know - I mistook it for the main fcc repo

2020-10-13 11:57 UTC, raisedadead commented
We haven't yet integrated Crowdin on this repo, but may do it if it helps.

2020-10-29 20:44 UTC, erictleung commented
@Kubaaa96 thanks for your pull request! I don't know Polish so I'm unable to review your work properly. Please find someone else who knows Polish who can create a GitHub review of this. Thanks!

2020-12-17 11:56 UTC, michal-dbrnowski requested changes
I think the author should review the whole text several more times. It is full of language mistakes and a few translation errors.

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- [Code Triage](https://www.codetriage.com/) - kolejne bardzo fajne narzędzie do znajdowania popularnych repozytoriów i filtrowania kwestii na podstawie języka.
"bardzo fajne" -> "ciekawe"
Let's be formal.

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- [Awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners) - GitHub repozytorium które gromadzi projekty z dobrymi bugami dla początkujących kontrybutorów i stosuje etykiety do ich o
"GitHub repozytorium" -> "repozytorium na GitHubie"
Loan translation.

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- [Open Source Guides](https://opensource.guide/) - Zbiór poradników dla pojedyńczych, grup i firm które chcą się nauczyć jak kontrybuować do projektów otwartego oprogramowania.
"dla pojedyńczych, grup i firm które" -> "dla wszystkich, którzy"
Loan translation. Btw, "pojedyńczych" is misspelled.
"nauczyć jak" -> "nauczyć, jak"
Punctuation mistake.

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- [Contribute to Open Source](https://github.com/danthareja/contribute-to-open-source) -  Naucz się jak działają i przepływają informacje na GitHubie poprzez kontrybuowanie do projektów symulacyjnych
"  Naucz się jak działają i przepływają informacje na GitHubie" -> " Naucz się jak działa GitHub"
"projektów symulacyjnych" -> "projektów symulowanych"
This sentence just doesn't make any sense.

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- [A to Z Resources for Students](https://github.com/dipakkr/A-to-Z-Resources-for-Students) - Upożądkowana lista poradników i możliwości dla studentów do nauki nowego języka programowania.
"Upożądkowana" -> "Uporządkowana"
Misspelling.

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- [Pull Request Roulette](http://www.pullrequestroulette.com/) - Ta strona zawiera listę pull request-ów zgłoszonych do przejrzenia należących do projektów otwartego oprogramowania  znajdujących się
"pull request-ów" -> "pull requestów"
Punctuation mistake.

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- ["How to Contribute to an Open Source Project on GitHub" by Egghead.io](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) - Poradnik krok po kroku w formie filmu o t
"o tym jak" -> "o tym, jak"
Punctuation mistake.

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- [Contributing to Open Source: A Live Walkthrough from Beginning to End](https://medium.com/@kevinjin/contributing-to-open-source-walkthrough-part-0-b3dc43e6b720) - Przewodnik o świecie kontrybuowan
"Przewodnik o świecie (...) głównej gałęzi." -> "Przewodnik o świecie kontrybuowania do otwartego oprogramowania zawiera wszystko, od wybrania odpowiedniego projektu, przez pracę na zgłoszoną kwestią *(ang. issue)*, aż do stworzenia własnego PR (Pull Request) i przyłączenia go do głównej gałęzi."
A lot of mistakes.

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- ["How to Contribute to Open Source Project by" Sarah Drasner](https://css-tricks.com/how-to-contribute-to-an-open-source-project/) - W tym poradniką autorzy skupiają się na zasadniczych zasadach ko
"W tym poradniką" -> "W tym poradniku"
Misspelling.
"kontrybuowania pull request-a" -> "kontrybuowania" or "tworzenia pull requestów"
Can't do both.
"do nie swojego" -> "do cudzego"

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- ["How to Contribute to Open Source Project" by Maryna Z](https://rubygarage.org/blog/how-contribute-to-open-source-projects) - Ten artykuł skierowany jest głównie w kierunku zespołów biznesowych (a
"w kierunku" -> "do"
Phraseological mistake.
"gdzie mówi o tym Czemu, Jak i po co" -> "i mówi o tym dlaczego, jak i po co"

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- ["start-here-guidelines" by Andrei](https://github.com/zero-to-mastery/start-here-guidelines) -Wskazówki jak działa społeczność GitHuba i na jakich zasadach opiera się kontrybuowanie do projektów O
" do celów edukacyjnych i do celów praktycznych" -> " do celów edukacyjnych i praktycznych"

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- [Good First Bugs](https://bugzil.la/sw:%22[good%20first%20bug]%22&limit=0) - bugi które programiści zidentyfikowali za dobre do wprowadzenia do projektu.
"bugi które programiści zidentyfikowali za dobre do wprowadzenia do projektu." -> "bugi, które programiści uznali za dobre wprowadzenie do projektu."
At this point I burst out laughing. 😂

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- [Mentored Bugs](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=mentor%3A%40) - bugi które mają mentora przypisanego, który będzie na IRC aby pomóc ci kiedy utkniesz podczas naprawiania owego
"mentora przypisanego" -> "przypisanego mentora"
Syntax mistake.
"aby pomóc ci kiedy" -> "aby pomóc ci, kiedy"
Punctuation mistake.
"owego" -> "tego"
It's not a poem.

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- [What Can I Do For Mozilla](https://whatcanidoformozilla.org/) -  Dowiedz się nad czym możęsz pracować poprzez odpowiedźna kilka pytań dotyczących twoich umiejętności i zainteresowań.
"Dowiedz się (...) i zainteresowań." -> "Dowiedz się, nad czym możesz pracować poprzez odpowiedź na kilka pytań dotyczących twoich umiejętności i zainteresowań."
A lot of mistakes.

2020-12-17 11:56 UTC, michal-dbrnowski commented on README-PL.md
> +- [Start Mozilla](https://twitter.com/StartMozilla) - Konto na Twitterze, które tweetuje na temat kwestii odpowiadających początkującym kontrybutorom w środowisku Mozilli.
"odpowiadających początkującym kontrybutorom" -> "odpowiednich dla początkujących kontrybutorów"
Logical mistake.

2020-12-18 12:59 UTC, michal-dbrnowski approved these changes
Much better than last time. I think the text is ready to be published.

2020-12-22 23:56 UTC, erictleung approved these changes

2020-12-22 23:57 UTC, merged

2020-12-22 23:58 UTC, erictleung commented
@michal-dbrnowski thanks for taking time to review this translation!! ✨ 

@Kubaaa96 congrats on contributing! Thanks for taking the time to make the initial translation and update it with feedback! 😄