Translated README.md File To Hindi Language
freeCodeCamp/how-to-contribute-to-open-source pull request #462
Opened 2020-10-13 12:19 UTC by everydaycodings

Created a File named README-HI.md for the Hindi Translation of README.md File

2020-10-13 16:57 UTC, AryanMangale commented
It seems like the translations are not very human, more like generic, formal language translations from Google.

2020-10-14 02:17 UTC, everydaycodings commented
This is a Human Translation  not from google translation I have made this with the help of my Hindi Teacher.
Anyway you can check it.

2020-10-15 11:27 UTC, vivek80801 requested changes

2020-10-15 11:27 UTC, vivek80801 commented on README-HI.md
> +- [Contributing to Open Source: A Live Walkthrough from Beginning to End](https://medium.com/@kevinjin/contributing-to-open-source-walkthrough-part-0-b3dc43e6b720) - एक ओपन सोर्स योगदान के इस पूर्वाभ
पीआर or पुल अनुरोध

2020-10-15 11:27 UTC, vivek80801 commented on README-HI.md
> +- ["start-here-guidelines" by Andrei](https://github.com/zero-to-mastery/start-here-guidelines) - ओपनसैट खेल की दुनिया में शुरू होता है, ओपनसोर्स खेल के मैदान में शुरू होता है। विशेष रूप से शिक्षा और
ओपनसैट or ओपनसोर्स

2020-10-15 11:27 UTC, vivek80801 commented on README-HI.md
> +Search links that point directly to suitable issues to contribute to on GitHub.
ऐसे लिंक खोजें जो सीधे GitHub पर योगदान करने के लिए उपयुक्त मुद्दों की ओर इशारा करते हैं।

2020-10-15 11:27 UTC, vivek80801 commented on README-HI.md
> +## मोज़िला का योगदानकर्ता पारिस्थितिकी तंत्र
पारिस्थितिकी तंत्र or इकोसिस्टम

2020-10-15 11:27 UTC, vivek80801 commented on README-HI.md
> +- [Good First Bugs](https://bugzil.la/sw:%22[good%20first%20bug]%22&limit=0) - बग जो डेवलपर्स ने परियोजना के लिए एक अच्छा परिचय के रूप में पहचाना है।
बग or मुद्दा

2020-10-15 11:27 UTC, vivek80801 commented on README-HI.md
> +- [Mentored Bugs](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=mentor%3A%40) - बग जो एक संरक्षक को सौंपा गया है, जो आईआरसी पर आपकी मदद करेगा जब आप एक फिक्स पर काम करते समय फंस जाते हैं।
बग or मुद्दा

2020-10-15 11:27 UTC, vivek80801 commented on README-HI.md
> +- [केवल पहले टाइमर](https://kentcdodds.com/blog/first-timers-only/) by [@kentcdodds](https://github.com/kentcdodds)
पहलीबार योगदानकर्ताओ के लिए

2020-10-15 11:27 UTC, vivek80801 commented on README-HI.md
> +- [ओपन सोर्स पर दया लाएं](https://web.archive.org/web/20201009150545/https://www.hanselman.com/blog/bring-kindness-back-to-open-source) by [@shanselman](https://github.com/shanselman)
ओपन सोर्स पर  दयालुता लाएं

2020-10-15 11:27 UTC, vivek80801 commented on README-HI.md
> +- [एक बिटर गाइड टू ओपन सोर्स](https://medium.com/codezillas/a-bitter-guide-to-open-source-a8e3b6a3c1c4) by [@ken_wheeler](https://medium.com/@ken_wheeler)
बिटर or बेहतर

2020-10-15 11:27 UTC, vivek80801 commented on README-HI.md
> +## स्रोत पुस्तकें खोलें
ओपन सोर्स किताबे

2020-10-15 11:27 UTC, vivek80801 commented on README-HI.md
> +- [First Timers Only](https://www.firsttimersonly.com/) - कीड़े की एक सूची जिसे "पहले-टाइमर-केवल" लेबल किया जाता है।
कीड़े?

2020-10-15 11:31 UTC, vivek80801 commented
"bugs" are not translated correctly. 
you can use मुद्दा insted of बग्स, कीड़े etc.

2020-10-16 20:41 UTC, erictleung commented
@vivek80801 thanks for your comments and feedback!

If you would like to get GitHub commit credit for helping so much with these translations, might I suggest to use the [suggest changes](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request#applying-a-suggested-change) feature in GitHub? This will allow you to directly make those suggested change you have commented and @everydaycodings can more quickly incorporate those changes.

2020-10-17 03:41 UTC, everydaycodings commented
> @vivek80801 thanks for your comments and feedback!
> 
> If you would like to get GitHub commit credit for helping so much with these translations, might I suggest to use the [suggest changes](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request#applying-a-suggested-change) feature in GitHub? This will allow you to directly make those suggested change you have commented and @everydaycodings can more quickly incorporate those changes.

Ya @vivek80801 use  [suggest changes](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request#applying-a-suggested-change)  so that I can more quickly Incorporate those changes.

2020-10-17 17:39 UTC, vivek80801 commented
@erictleung  and @everydaycodings 

I don't know how to use that feature. I read docs on `Incorporating feedback in your pull request`. But I will need write access.

2020-10-18 04:41 UTC, everydaycodings commented
Ok @vivek80801 when you Complete your editing then please notify me I will merge it to my Pull Request 

Thanku

2020-10-19 10:30 UTC, vivek80801 commented
@everydaycodings 
> Ok @vivek80801 when you Complete your editing then please notify me I will merge it to my Pull Request
> 
> Thanku

Can You explain what to do from my end ?

2020-10-29 21:05 UTC, erictleung commented
@vivek80801 see below to access the review button which you have done.

![](https://docs.github.com/assets/images/help/commits/hover-comment-icon.gif)

But then you can access a suggestion button shown as the left-most symbols in the comment box. It has a plus-minus sign on a document.

![](https://docs.github.com/assets/images/help/pull_requests/comment-field.png)

After clicking on it, you should see a code block insertion that you can edit.

![](https://docs.github.com/assets/images/help/pull_requests/suggestion-block.png)

Source: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request

2020-11-25 11:31 UTC, anmolsahu2k commented on README-HI.md
> +- [डायरेक्ट गिटहब खोजता है](#direct-github-searches)
> I think this should be [डायरेक्ट गिटहब खोजें ](#direct-github-searches)
> 
> ```diff
> - [डायरेक्ट गिटहब खोजता है](#direct-github-searches)
> 
> + [डायरेक्ट गिटहब खोजें ](#direct-github-searches)
> ```

Yes this is more accurate

2020-11-25 11:34 UTC, anmolsahu2k commented on README-HI.md
> +- [स्रोत पुस्तकें खोलें](#open-source-books)
Yes, this is more accurate

2020-11-25 11:38 UTC, anmolsahu2k requested changes
The comments have to be reviewed for changes.

2020-11-30 15:54 UTC, dumbcoder7 commented on README-HI.md
> +यह उन लोगों के लिए संसाधनों की एक सूची है जो ओपन सोर्स में योगदान करने के लिए नए हैं।
```suggestion
यह उन लोगों के लिए संसाधनों की एक सूची हैं जो ओपन सोर्स में योगदान करने के लिए नए हैं।
```

2020-11-30 15:54 UTC, dumbcoder7 commented on README-HI.md
> +यदि आपके कोई प्रश्न या टिप्पणी है, तो कृपया एक मुद्दा बनाएं।
```suggestion
यदि आपके कोई प्रश्न या टिप्पणी हैं, तो कृपया एक मुद्दा बनाएं।
```

2020-11-30 16:21 UTC, dumbcoder7 commented on README-HI.md
> +- [Code Triage](https://www.codetriage.com/) - अन्य, वास्तव में अच्छा, लोकप्रिय रिपॉजिटरी और भाषा द्वारा फ़िल्टर किए गए मुद्दों को खोजने के लिए उपकरण।
```suggestion
- [Code Triage](https://www.codetriage.com/) - लोकप्रिय रिपॉजिटरी और भाषा द्वारा फ़िल्टर किए गए मुद्दों को खोजने के लिए उपकरण।
```

2020-11-30 16:21 UTC, dumbcoder7 commented on README-HI.md
> +- [45 Github Issues Dos and Don’ts](https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612) -GitHub पर Do's और Don'ts।
```suggestion
- [45 Github Issues Dos and Don’ts](https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612) -GitHub के Do's और Don'ts।
```

2020-11-30 16:21 UTC, dumbcoder7 commented on README-HI.md
> +- [GitHub Guides](https://guides.github.com/) - कैसे प्रभावी रूप से GitHub का उपयोग करने के बारे में बुनियादी गाइड।
Feels unnatural

```suggestion
- [GitHub Guides](https://guides.github.com/) - प्रभावी रूप से GitHub का उपयोग करने के बारे में बुनियादी गाइड।
```

2020-11-30 16:21 UTC, dumbcoder7 commented on README-HI.md
> +- [Contribute to Open Source](https://github.com/danthareja/contribute-to-open-source) - एक सिमुलेशन परियोजना के लिए कोड का योगदान करके GitHub वर्कफ़्लो जानें।
- Corrected transliteration of 'Simulation'

- Better not to translate the word 'project'

```suggestion
- [Contribute to Open Source](https://github.com/danthareja/contribute-to-open-source) - एक सिम्युलेशन प्रोजेक्ट के लिए कोड का योगदान करके GitHub वर्कफ़्लो जानें।
```

2020-11-30 16:21 UTC, dumbcoder7 commented on README-HI.md
> +- [Linux Foundation's Open Source Guides for the Enterprise](https://www.linuxfoundation.org/resources/open-source-guides/) - लिनक्स फाउंडेशन के स्रोत स्रोत खोलने के लिए गाइड।
Poorly translated

```suggestion
- [Linux Foundation's Open Source Guides for the Enterprise](https://www.linuxfoundation.org/resources/open-source-guides/) - लिनक्स फाउंडेशन कि तरफ से ओपन सोर्स प्रोजेक्ट्स के लिए गाइड।
```

2020-11-30 16:21 UTC, dumbcoder7 commented on README-HI.md
> +- [CSS Tricks An Open Source Etiquette Guidebook](https://css-tricks.com/open-source-etiquette-guidebook/) - केंट सी। डोड्स एंड सारा ड्रैसनर द्वारा लिखित एक ओपन सोर्स शिष्टाचार गाइडबुक।
Fixed name transliteration

```suggestion
- [CSS Tricks An Open Source Etiquette Guidebook](https://css-tricks.com/open-source-etiquette-guidebook/) - केंट सी. डोड्स एवं सारा ड्रैसनर द्वारा लिखित एक ओपन सोर्स शिष्टाचार गाइडबुक।
```

2020-11-30 16:21 UTC, dumbcoder7 commented on README-HI.md
> +- [Contributing to Open Source: A Live Walkthrough from Beginning to End](https://medium.com/@kevinjin/contributing-to-open-source-walkthrough-part-0-b3dc43e6b720) - एक ओपन सोर्स योगदान के इस पूर्वाभ
पुल रिक्वेस्ट Feels best

2020-11-30 16:21 UTC, dumbcoder7 commented on README-HI.md
> +- [Pull Request Roulette](http://www.pullrequestroulette.com/) - इस साइट में जीथब पर होस्ट किए गए ओपन सोर्स प्रोजेक्ट से संबंधित समीक्षा के लिए प्रस्तुत पुल अनुरोधों की एक सूची है।
Don't transliterate 'GitHub'

```suggestion
- [Pull Request Roulette](http://www.pullrequestroulette.com/) - इस साइट में GitHub पर होस्ट किए गए ओपन सोर्स प्रोजेक्ट से संबंधित समीक्षा के लिए प्रस्तुत पुल अनुरोधों की एक सूची है।
```

2020-11-30 16:21 UTC, dumbcoder7 commented on README-HI.md
> +- ["How to Contribute to Open Source Project by" Sarah Drasner](https://css-tricks.com/how-to-contribute-to-an-open-source-project/) - वे गिटहब पर किसी और की परियोजना के लिए एक पुल अनुरोध (पीआर) का य
```suggestion
- ["How to Contribute to Open Source Project by" Sarah Drasner](https://css-tricks.com/how-to-contribute-to-an-open-source-project/) - वे गिटहब पर किसी और की परियोजना के लिए एक पुल अनुरोध (पीआर) का योगदान करने पर ध्यान केंद्रित कर रहे हैं।
```

2020-11-30 16:21 UTC, dumbcoder7 commented on README-HI.md
> +- ["How to get started with Open Source by" Sayan Chowdhury](https://www.hackerearth.com:443/getstarted-opensource/) - यह लेख अपनी पसंदीदा भाषा रुचि के आधार पर शुरुआती के लिए स्रोत खोलने में योगदान क
```suggestion
- ["How to get started with Open Source by" Sayan Chowdhury](https://www.hackerearth.com:443/getstarted-opensource/) - यह लेख अपनी पसंदीदा भाषा रुचि के आधार पर नौसिखियों के लिए ओपन सोर्स में योगदान करने के लिए संसाधनों को शामिल करता है।
```

2020-11-30 16:21 UTC, dumbcoder7 commented on README-HI.md
> +- ["How to Contribute to Open Source Project" by Maryna Z](https://rubygarage.org/blog/how-contribute-to-open-source-projects) - यह व्यापक लेख व्यवसायों की ओर निर्देशित है (लेकिन व्यक्तिगत योगदानकर्त
```suggestion
- ["How to Contribute to Open Source Project" by Maryna Z](https://rubygarage.org/blog/how-contribute-to-open-source-projects) - यह व्यापक लेख व्यवसायों की ओर निर्देशित है (लेकिन व्यक्तिगत योगदानकर्ताओं के लिए भी उपयोगी है) जहां यह बात करता है कि क्यों, कैसे, और क्या-क्या ओपन-सोर्स प्रोजेक्ट्स में योगदान करना उचित है।
```

2020-11-30 16:21 UTC, dumbcoder7 commented on README-HI.md
> +- ["start-here-guidelines" by Andrei](https://github.com/zero-to-mastery/start-here-guidelines) - ओपनसैट खेल की दुनिया में शुरू होता है, ओपनसोर्स खेल के मैदान में शुरू होता है। विशेष रूप से शिक्षा और
```suggestion
- ["start-here-guidelines" by Andrei](https://github.com/zero-to-mastery/start-here-guidelines) - ओपनसोर्स खेल की दुनिया ओपनसोर्स प्लेग्राउंड में शुरू होती है। विशेष रूप से शिक्षा और व्यावहारिक अनुभव उद्देश्यों के लिए रचा गया हैं।
```

2020-11-30 18:55 UTC, anmolsahu2k commented on README-HI.md
> +- [डायरेक्ट गिटहब खोजता है](#direct-github-searches)
> How about
> 
> ```diff
> - [डायरेक्ट गिटहब खोजें ](#direct-github-searches)
> 
> + [डायरेक्ट गिटहब खोजना](#direct-github-searches)
> ```

No, the correct one should be-
```diff
- [डायरेक्ट गिटहब खोजता है](#direct-github-searches)
+ [डायरेक्ट गिटहब खोजें](#direct-github-searches)
```

2021-01-02 11:42 UTC, AniketSawale requested changes
इस काम के तहत लाइसेंस प्राप्त है।[ क्रिएटिव कॉमन्स एट्रिब्यूशन-शेयरअलाइल 4.0 इंटरनेशनल लाइसेंस.](https://creativecommons.org/licenses/by-sa/4.0/)

2021-01-02 11:47 UTC, AniketSawale approved these changes

2021-01-02 11:47 UTC, AniketSawale commented on README-HI.md
> +<a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://licensebuttons.net/l/by-sa/4.0/88x31.png" /></a><br />इ
<a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://licensebuttons.net/l/by-sa/4.0/88x31.png" /></a><br />इस काम के तहत लाइसेंस प्राप्त है। <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">क्रिएटिव कॉमन्स एट्रिब्यूशन-शेयरअलाइल 4.0 इंटरनेशनल लाइसेंस</a>.

2021-03-01 04:34 UTC, Jeevan-Kiran-Lenka commented
Hey! I have some options in my mind for this since we are translating the page using a google translator some words like व्यक्तिगत योगदानकर्ताओं, पूर्वाभ्यास, योगदानकर्ताओं are not so familiar around Hindi community also Hindi people nowadays don't use that.

So instead of using hard words as shown above we can simplify it into bits that the general public can understand as when I was reading the readme I have to do google searches for Hindi words to get the meaning of that words

Other than that great work

2021-05-15 13:11 UTC, saranshusa approved these changes

2021-05-27 16:00 UTC, Umesh-01 approved these changes

2022-01-03 19:24 UTC, merged