Add helpful link
freeCodeCamp/how-to-contribute-to-open-source pull request #463
Opened 2020-10-13 17:14 UTC by AryanMangale

Added a link to ##Using Verison Control

2020-10-29 20:34 UTC, erictleung commented on README.md
> +- [Git Cheat Cheets](https://devhints.io/?q=git) - A set of grahical cheat sheets on git
For consistency.

```suggestion
- [Git Cheat Cheets](https://devhints.io/?q=git) - A set of grahical cheat sheets on git.
```

2020-10-29 20:34 UTC, erictleung requested changes
Thanks for the link. It looks good, just want to keep it consistent with the rest. See comment.

2020-10-29 20:38 UTC, nhcarrigan commented on README.md
> +- [Git Cheat Cheets](https://devhints.io/?q=git) - A set of grahical cheat sheets on git
```suggestion
- [Git Cheat Cheets](https://devhints.io/?q=git) - A set of graphical cheat sheets on git.
```

Can we correct the typo as well? 🙂

2022-06-10 04:24 UTC, erictleung approved these changes
LGTM! 👍 Thanks for taking the time to find this link and adding it! It'll be useful for others to use when learning git ✨

2022-06-10 04:25 UTC, merged