Translated README-MS.md to Malay Language
freeCodeCamp/how-to-contribute-to-open-source pull request #483
Opened 2020-11-04 00:36 UTC by EugeneGohh

* Feel free to review my translation looking forward to see some feedback.

2020-11-04 20:32 UTC, erictleung commented
Corresponding issue https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues/482

2020-11-11 10:30 UTC, RezaPurut requested changes
Great effort in translating this repo to Malay. I have reviewed this and there are few things that need to be fixed

2020-11-11 10:30 UTC, RezaPurut commented on README-MALAY.md
> +## Menggunakan Pengawalan Versi
- change `Pengawalan` to `Kawalan`

2020-11-11 10:30 UTC, RezaPurut commented on README-MALAY.md
> +- [Think Like (a) Git](http://think-like-a-git.net/) - Pengenalan Git untuk "pemula maju", tetapi masih berusaha, untuk memberi anda strategi mudah untuk bereksperimen dengan selamat dengan git.
- maybe can change word `berusaha` to `bersusah-payah`

2020-11-11 10:30 UTC, RezaPurut commented on README-MALAY.md
> +- [Firefox DevTools](http://firefox-dev.tools/) - laman web yang dikhaskan untuk bug yang difailkan untuk alat pembangun dalam penyemak imbas Firefox.
- add `(developer tools)` next to word `alat pembangun`
- add `(browser)` next to word `penyemak imbas`

2020-11-11 10:30 UTC, RezaPurut commented on README-MALAY.md
> +- [Try Git](https://try.github.io/) - Belajar Git dalam 15 minit dalam laman anda.
- change `laman` to `penyemak imbas (browser)`
- add `secara percuma` at the end of the word

2020-11-11 10:30 UTC, RezaPurut commented on README-MALAY.md
> +- [Oh shit, git!](https://ohshitgit.com/) - cara mengatasi kesalahan `git` yang biasa dijelaskan dalam bahasa Inggeris biasa; lihat juga [Dangit, git!](https://dangitgit.com/) untuk halaman tanpa sum
- remove `biasa` before dijelaskan. So, it will becomes `yang dijelaskan`
- change `sumpah` to `carutan`

2020-11-11 10:30 UTC, RezaPurut commented on README-MALAY.md
> +- [GitHub Flow](https://www.youtube.com/watch?v=juLIxo42A_s) (42:06) - bagaimana menarik tarik permintaan diajar oleh GitHub
- change `tarik permintaan` to `permintaan tarik`
- add `(pull request)` next to word `permintaan tarik` if you had changed as above

2020-11-11 10:30 UTC, RezaPurut commented on README-MALAY.md
> +- [GitHub Learning Resources](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/git-and-github-learning-resources) - Git dan GitHub sumber pelajaran
- change `Git dan GitHub sumber pelajaran` to `sumber pembelajaran Git and GitHub`

2020-11-11 10:30 UTC, RezaPurut commented on README-MALAY.md
> +- [Git Best Practices](https://sethrobertson.github.io/GitBestPractices/) - Lakukan Selalunya, Sempurna Kemudian, Terbitkan Sekali: Git Amalan Terbaik
- change `Lakukan` to `Komit`

2020-11-11 10:30 UTC, RezaPurut commented on README-MALAY.md
> +- [Git Interactive Tutorial](https://learngitbranching.js.org/) - Belajar Git secara visual dan interaktif
- change `Belajar Git secara visual dan interaktif` to `Belajar Git dengan cara paling visual dan interaktif`

2020-11-11 10:30 UTC, RezaPurut commented on README-MALAY.md
> +- [Producing Open Source Software](https://producingoss.com/) - Menghasilkan Perisian Sumber Terbuka adalah buku mengenai sisi manusia dalam pembangunan Sumber Terbuka. Ini menggambarkan bagaimana pr
- change `adalah` to `ialah`
- change `dijalankan` to `beroperasi`

2020-11-11 10:30 UTC, RezaPurut commented on README-MALAY.md
> +- [Up For Grabs](https://up-for-grabs.net/) - Mengandungi projek untuk penyumbang yang baru.
- change `Mengandungi projek untuk penyumbang yang baru` to `Mengandungi isu projek yang mesra penyumbang baru`.

2020-11-11 10:30 UTC, RezaPurut commented on README-MALAY.md
> +- [24 Pull Requests](https://24pullrequests.com) - 24 permintaan tarik adalah projek untuk mempromosikan kolaborasi Sumber Terbuka pada bulan Disember.
- add `(pull request)` next to word `permintaan tarik`

2020-11-13 07:56 UTC, EugeneGohh commented
> Great effort in translating this repo to Malay. I have reviewed this and there are few things that need to be fixed

Thank you for reviewing my Malay translation. :blush:  🙏

2020-11-16 04:23 UTC, erictleung commented
@RezaPurut thanks for taking time to review this translation!!

@EugeneGohh I see you have resolved each of the translation feedback, but I don't see any changed based on those suggestions. Let me know if there was anything wrong with those suggestions. Otherwise, I'll check back once you've pushed those changes to your pull request!

2020-11-16 06:40 UTC, EugeneGohh commented
> @RezaPurut thanks for taking time to review this translation!!
> 
> @EugeneGohh I see you have resolved each of the translation feedback, but I don't see any changed based on those suggestions. Let me know if there was anything wrong with those suggestions. Otherwise, I'll check back once you've pushed those changes to your pull request!

@erictleung Sorry I'm still new still not familiar with GitHub. I just updated it.

2020-11-23 04:44 UTC, EugeneGohh commented
> @RezaPurut thanks for taking time to review this translation!!
> 
> @EugeneGohh I see you have resolved each of the translation feedback, but I don't see any changed based on those suggestions. Let me know if there was anything wrong with those suggestions. Otherwise, I'll check back once you've pushed those changes to your pull request!

I have updated it can you help me check?

2020-11-25 09:16 UTC, RezaPurut requested changes
Good job. Just need to fix 2 more minor mistake that I overlooked in first review

2020-11-25 09:16 UTC, RezaPurut commented on README-MS.md
> +Jika anda mempunyai soalan atau komen, sila membuat satu isu tentang soalan atau komentar tersebut.
```suggestion
Jika anda mempunyai soalan atau komen, sila membuat satu isu tentang soalan atau komen tersebut.
```

2020-11-25 09:16 UTC, RezaPurut commented on README-MS.md
> +Jika anda jumpa sumber tambahan, sila menyumbang dengan membuat satu pull request.
```suggestion
Jika anda jumpa sumber tambahan, sila menyumbang dengan membuat satu 'pull request'.
```

2020-11-25 09:20 UTC, RezaPurut commented
@EugeneGohh please fix another 2 minor things. I already suggested the required changes for your convenience

2020-11-25 11:31 UTC, EugeneGohh commented
### How can I fix this?

![issue](https://user-images.githubusercontent.com/64187129/100222211-bd065800-2f54-11eb-92fd-332f989f31a6.jpg)

2020-11-25 11:32 UTC, EugeneGohh commented
> @EugeneGohh please fix another 2 minor things. I already suggested the required changes for your convenience

I have changed it. Thanks.

2020-11-26 11:13 UTC, RezaPurut commented
Not sure why the checks failed. This also happened on another PR #487 

Maybe @erictleung knows something about this.

2020-11-28 23:23 UTC, erictleung commented
@EugeneGohh thanks for making these changes! Don't worry about the CI failing. That's another issue.

2020-11-28 23:23 UTC, erictleung approved these changes
LGTM! 👍 Thanks for taking time to translate the README to Malay!! ✨

2020-11-28 23:23 UTC, merged