Completed The Task of Translation into Bengali
freeCodeCamp/how-to-contribute-to-open-source pull request #493
Opened 2020-12-14 07:18 UTC by ahammadshawki8

# What I have done:

- [x]  Created README-BANGLA.md file
- [x]  Added the README-BANGLE.md file's link in all other READMEs.
- [x]  Asked a member of my community to review the README-BANGLA.md file

## Comment:
I hope that these changes will be reviewed and the pull request will be accepted soon. Please let me know your suggestions/feedback.

2020-12-23 00:02 UTC, erictleung commented
@ahammadshawki8 thanks for the translation! One thing I would suggest is to change your `README-BANGLA.md` file name to `README-BN.md` to be consistent with the [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) language codes as the rest of the repository adheres to.

I hope that makes sense. Let me know if you have any questions.

2020-12-23 01:17 UTC, ahammadshawki8 commented
> @ahammadshawki8 thanks for the translation! One thing I would suggest is to change your `README-BANGLA.md` filename to `README-BN.md` to be consistent with the [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) language codes as the rest of the repository adheres to.
> 
> I hope that makes sense. Let me know if you have any questions.

Thanks for your suggestion. I will change the filename and all the links as soon as possible.

2020-12-23 01:38 UTC, ahammadshawki8 commented
I have checked the README-BN.md file again. There is no bug remaining. So, I think it is ready for merging.
Please let me know if you have any suggestions.
🙏🏼

2020-12-24 04:21 UTC, erictleung requested changes
Just some small comments.

Otherwise, thanks for translating! I don't have knowledge of Bengali so I'm unable to appropriately review this translation. I will keep this open for someone else who knows Bengali to review these changes.

2020-12-24 04:21 UTC, erictleung commented on README-BG.md
> +<!-- Do not translate this! -->
Why was this changed?

```suggestion
<!-- Do not translate this -->
```

2020-12-24 04:21 UTC, erictleung commented on README-BG.md
> + <!-- Do not translate this! --> <!-- Този превод се стреми да е по-скоро смислен, отколкото прецизно точен -->
And this?

```suggestion
 <!-- Do not translate this --> <!-- Този превод се стреми да е по-скоро смислен, отколкото прецизно точен -->
```

2020-12-24 04:21 UTC, erictleung commented on README-CN.md
> +        <td><a href="./README-BN.md">বাংলা</a></td>
For consistency

```suggestion
        <td><a href="./README-BN.md"> বাংলা </a></td>
```

2020-12-24 04:42 UTC, ahammadshawki8 commented
Ok I will work on it and ask my friend to review who know Bengali very well.

Thanks.

On Thu, 24 Dec 2020 10:22 am Eric Leung, <notifications@github.com> wrote:

> *@erictleung* requested changes on this pull request.
>
> Just some small comments.
>
> Otherwise, thanks for translating! I don't have knowledge of Bengali so
> I'm unable to appropriately review this translation. I will keep this open
> for someone else who knows Bengali to review these changes.
> ------------------------------
>
> In README-BG.md
> <https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/493#discussion_r548373010>
> :
>
> > @@ -1,11 +1,12 @@
>
> -<!-- Do not translate this -->
>
> +<!-- Do not translate this! -->
>
>
> Why was this changed?
> ⬇️ Suggested change
>
> -<!-- Do not translate this! -->
>
> +<!-- Do not translate this -->
>
>
> ------------------------------
>
> In README-BG.md
> <https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/493#discussion_r548373035>
> :
>
> > @@ -20,7 +21,7 @@
>
>  </ul>
>
>  </details>
>
>
>
> - <!-- Do not translate this --> <!-- Този превод се стреми да е по-скоро смислен, отколкото прецизно точен -->
>
> + <!-- Do not translate this! --> <!-- Този превод се стреми да е по-скоро смислен, отколкото прецизно точен -->
>
>
> And this?
> ⬇️ Suggested change
>
> - <!-- Do not translate this! --> <!-- Този превод се стреми да е по-скоро смислен, отколкото прецизно точен -->
>
> + <!-- Do not translate this --> <!-- Този превод се стреми да е по-скоро смислен, отколкото прецизно точен -->
>
>
> ------------------------------
>
> In README-CN.md
> <https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/493#discussion_r548373497>
> :
>
> > @@ -2,6 +2,7 @@
>
>      <tr>
>
>          <!-- Do not translate this table -->
>
>          <td><a href="./README.md"> English </a></td>
>
> +        <td><a href="./README-BN.md">বাংলা</a></td>
>
>
> For consistency
> ⬇️ Suggested change
>
> -        <td><a href="./README-BN.md">বাংলা</a></td>
>
> +        <td><a href="./README-BN.md"> বাংলা </a></td>
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/493#pullrequestreview-558326011>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANMOM636JR6GENVIGEAR7PLSWK6XDANCNFSM4U2I62WA>
> .
>

2020-12-24 08:58 UTC, EssamSami5155 approved these changes
Everything looks fine in Bengali. There is no problem with the translation. I think it is ready for merging. Good job @ahammadshawki8 .

2020-12-25 01:24 UTC, erictleung approved these changes
LGTM! 👍 Thanks for taking the time to translate and update all the other translation files! ✨

2020-12-25 01:24 UTC, erictleung commented
@EssamSami5155 thanks for your review!

2020-12-25 01:24 UTC, merged

2020-12-25 01:33 UTC, ahammadshawki8 commented
Thank you very much.

On Fri, Dec 25, 2020 at 7:24 AM Eric Leung <notifications@github.com> wrote:

> Merged #493
> <https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/493>
> into master.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/493#event-4148314056>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANMOM6YKOMTIWMD2TCQQJ5DSWPSVZANCNFSM4U2I62WA>
> .
>

2021-01-02 11:14 UTC, AniketSawale commented
I reviewed and it seems everything is fine in Bengali.

2021-01-02 11:16 UTC, AniketSawale reviewed
Everything is fine in the Bengali version.

2021-01-26 19:11 UTC, BKD471 commented
Yes everything seems fine with Bengali translation ..good job mate :)