Translated README.md in marathi
freeCodeCamp/how-to-contribute-to-open-source pull request #499
Opened 2021-01-03 14:12 UTC by praj9719

2021-01-04 08:48 UTC, erictleung commented
@praj9719 thanks for the translation! I'm unable to review your pull request because I don't know Marathi. I will keep this open until someone who knows Marathi is able to review your work before I can merge it.

2021-02-09 13:18 UTC, kcoder63 commented
can i review it? i know marathi well

2021-02-12 00:59 UTC, erictleung commented
@kcoder63 go for it! Take a look at the files here https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/499/files and go down to where it says `README-MR.md`. You might have to click on "Load diff" to expand the file because it is too big to show initially. 

To review the text and make suggestions, you can hover and click on the left hand side of the file when you see a plus sigh (`+`) pop up. From there you can make suggestions by pressing <kbd>Ctrl+g</kbd> while in the comment box.

2021-02-12 03:44 UTC, kcoder63 commented
Thank you , it can take some 2-3 days if that's fine

2021-02-12 08:45 UTC, kcoder63 requested changes

2021-02-12 08:45 UTC, kcoder63 commented on README-MR.md
> +- [GitHub Guides](https://guides.github.com/) - GitHub प्रभावीपणे कसे वापरावे याबद्दल मूलभूत मार्गदर्शक.
```suggestion
- [GitHub Guides](https://guides.github.com/) - गिटहब प्रभावीपणे कसे वापरावे याबद्दल मूलभूत मार्गदर्शक.
```

2021-02-12 08:45 UTC, kcoder63 commented on README-MR.md
> +- [Pull Request Roulette](http://www.pullrequestroulette.com/) - या साइटवर गीथबवर होस्ट केलेल्या ओपन सोर्स प्रकल्पांच्या पुनरावलोकनासाठी सबमिट केलेल्या पुल विनंत्यांची यादी आहे.
```suggestion
- [Pull Request Roulette](http://www.pullrequestroulette.com/) - या साइटवर गिटहब वर होस्ट केलेल्या ओपन सोर्स प्रकल्पांच्या पुनरावलोकनासाठी सबमिट केलेल्या पुल विनंत्यांची यादी आहे.
```

2021-02-12 08:45 UTC, kcoder63 commented on README-MR.md
> +## डायरेक्ट गीथब सर्च
```suggestion
## डायरेक्ट गिटहब सर्च
```

2021-02-12 08:45 UTC, kcoder63 commented on README-MR.md
> +GitHub वर सहयोग देण्यासाठी थेट योग्य मुद्द्यांकडे निर्देश करणारे दुवे शोधा.
```suggestion
गिटहब वर सहयोग देण्यासाठी थेट योग्य मुद्द्यांकडे निर्देश करणारे दुवे शोधा.
```

2021-02-12 08:45 UTC, kcoder63 commented on README-MR.md
> +- [GitHub Learning Resources](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/git-and-github-learning-resources) - Git आणि GitHub शिक्षण संसाधने
```suggestion
- [GitHub Learning Resources](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/git-and-github-learning-resources) - गिट आणि गिटहब शिक्षण संसाधने
```

2021-02-24 07:01 UTC, PrajaktaSathe commented
> @praj9719 thanks for the translation! I'm unable to review your pull request because I don't know Marathi. I will keep this open until someone who knows Marathi is able to review your work before I can merge it.

@erictleung 
I know Marathi well...and can check the doc once too! 😄 
Can you assign me this?
Thanks!

2021-02-24 07:05 UTC, kcoder63 commented
> > @praj9719 thanks for the translation! I'm unable to review your pull request because I don't know Marathi. I will keep this open until someone who knows Marathi is able to review your work before I can merge it.
> 
> @erictleung
> I know Marathi well...and can check the doc once too! 😄
> Can you assign me this?
> Thanks!

I already reviewed it here

2021-02-24 07:11 UTC, PrajaktaSathe commented on README-MR.md
> +आपल्याला अतिरिक्त संसाधने आढळल्यास, कृपया पुल विनंतीस सहयोग द्या.
How about - आपल्याला अतिरिक्त संसाधने आढळल्यास, कृपया pull requestनी सहयोग द्या.

2021-02-24 07:13 UTC, PrajaktaSathe commented on README-MR.md
> +- [नवीन मुक्त स्त्रोत योगदानकर्त्यांसाठी उपयुक्त लेख](#नवीन-मुक्त-स्त्रोत-योगदानकर्त्यांसाठी-उपयुक्त-लेख)
I think this would sound better - नवीन open-source योगदानकर्त्यांसाठी उपयुक्त लेख

2021-02-24 07:19 UTC, PrajaktaSathe commented on README-MR.md
> +- [Open Source Guides](https://opensource.guide/) - लोक, समुदाय आणि कंपन्यांना ओपन सोर्स प्रोजेक्टमध्ये कसे चालवायचे आणि योगदान कसे द्यायचे हे शिकू इच्छितात अशा स्त्रोतांचे संग्रह.
लोक, समुदाय आणि कंपन्यांना ओपन सोर्स प्रोजेक्टमध्ये कसे वापरायचे आणि योगदान कसे द्यायचे हे शिकू इच्छिणाऱ्यांसाठी स्त्रोतांचे संग्रह.

2021-02-24 07:28 UTC, PrajaktaSathe commented on README-MR.md
> +- [How to choose (and contribute to) your first Open Source project](https://github.com/collections/choosing-projects) by [@GitHub](https://github.com/github)
[आपला प्रथम मुक्त स्त्रोत प्रकल्प कसा निवडावा (आणि त्यात सहयोग द्यावा)](https://github.com/collections/choosing-projects) by [@GitHub](https://github.com/github)

2021-02-24 07:31 UTC, PrajaktaSathe commented on README-MR.md
> +- [How to make your first Open Source contribution in just 5 minutes](https://www.freecodecamp.org/news/how-to-make-your-first-open-source-contribution-in-just-5-minutes-aaad1fc59c9a/) by [@roshanjos
```suggestion
[केवळ 5 मिनिटांत आपले प्रथम मुक्त स्त्रोत योगदान कसे करावे](https://www.freecodecamp.org/news/how-to-make-your-first-open-source-contribution-in-just-5-minutes-aaad1fc59c9a/) by [@roshanjossey](https://github.com/Roshanjossey/)
```

2021-03-25 23:22 UTC, erictleung approved these changes
LGTM! 👍

2021-03-25 23:22 UTC, merged