Update README-NL.md
freeCodeCamp/how-to-contribute-to-open-source pull request #549
Opened 2021-03-15 11:05 UTC by herkura

Closed #480

2021-03-15 11:07 UTC, herkura commented
@erictleung  pls see this issue
i have some problem in checks

2021-03-25 22:51 UTC, erictleung commented
@herkura thanks for the translations! I don't have the expertise to review this.

@Lorretje are you able to review this translation? If not, no worries!

2021-03-25 22:56 UTC, erictleung commented
@herkura because of some other pull requests that were merged for this README, there are some conflicts that can't be completed in GitHub's web interface. So you'll need to pull updates before going forward.

```
git clone https://github.com/herkura/how-to-contribute-to-open-source
cd how-to-contribute-to-open-source
git remote add upstream https://github.com/freeCodeCamp/how-to-contribute-to-open-source
git fetch upstream

git checkout update-README-NL
git rebase upstream/master
```

Then you can make your changes before pushing your changes back up to GitHub.

I hope that helps.

2021-03-26 03:32 UTC, herkura commented
@erictleung Thanks for the update but is did the same process that you mentioned .. I will try again Thanks again

2021-03-26 08:50 UTC, noah-vdv requested changes
Mostly a couple of nitpicks.
Also, probably a question for @erictleung : Should titles of articles, sites, etc. be translated or not?

2021-03-26 08:50 UTC, noah-vdv commented on README-NL.md
> +- [A tot Z bronnen voor studenten](https://github.com/dipakkr/A-to-Z-Resources-for-Students) -Een Open Source Etiquette-handboek, geschreven door Kent C. Dodds en Sarah Drasner.An Open Source Etiquet
```suggestion
- [A tot Z bronnen voor studenten](https://github.com/dipakkr/A-to-Z-Resources-for-Students) -Een Open Source Etiquette-handboek, geschreven door Kent C. Dodds en Sarah Drasner.
```

2021-03-26 08:50 UTC, noah-vdv commented on README-NL.md
> +- [GitHub-handleidingen](https://guides.github.com/) -basisgidsen voor het effectief gebruiken van GitHub.
```suggestion
- [GitHub-handleidingen](https://guides.github.com/) - basisgidsen voor het effectief gebruiken van GitHub.
```

2021-03-26 08:50 UTC, noah-vdv commented on README-NL.md
> +- [Code Triage](https://www.codetriage.com/) -een andere, erg leuke tool voor het vinden van populaire repositories en problemen gefilterd op taal.
```suggestion
- [Code Triage](https://www.codetriage.com/) - een andere, erg leuke tool voor het vinden van populaire repositories en problemen gefilterd op taal.
```

2021-03-26 08:50 UTC, noah-vdv commented on README-NL.md
> +- [Pull Request Roulette](http://www.pullrequestroulette.com/) - Deze site heeft een lijst met pull-aanvragen die ter beoordeling zijn ingediend en behoren tot Open Source-projecten die op Github wor
```suggestion
- [Pull Request Roulette](http://www.pullrequestroulette.com/) - Deze site heeft een lijst met pull requests die ter beoordeling zijn ingediend en behoren tot Open Source-projecten die op Github worden gehost.
```

2021-03-26 08:50 UTC, noah-vdv commented on README-NL.md
> +- [Bijdragen aan open source: een live walkthrough van begin tot eind](https://medium.com/@kevinjin/contributing-to-open-source-walkthrough-part-0-b3dc43e6b720) - Deze walkthrough van een open source
```suggestion
- [Bijdragen aan open source: een live walkthrough van begin tot eind](https://medium.com/@kevinjin/contributing-to-open-source-walkthrough-part-0-b3dc43e6b720) - Deze walkthrough van een open source-bijdrage omvat alles, van het kiezen van een geschikt project, het werken aan een probleem (issue), tot het samenvoegen van de PR.
```

2021-03-26 08:50 UTC, noah-vdv commented on README-NL.md
> +- ["Hoe u kunt bijdragen aan een open source-project door" Sarah Drasner](https://css-tricks.com/how-to-contribute-to-an-open-source-project/) - Ze concentreren zich op de essentie van het bijdragen
```suggestion
- ["Hoe u kunt bijdragen aan een open source-project" door Sarah Drasner](https://css-tricks.com/how-to-contribute-to-an-open-source-project/) - Ze concentreren zich op de essentie van het bijdragen van een pull request (PR) aan het project van iemand anders op GitHub.
```

2021-03-26 08:50 UTC, noah-vdv commented on README-NL.md
> +- ["Aan de slag met Open Source door" Sayan Chowdhury](https://www.hackerearth.com:443/getstarted-opensource/) -Dit artikel behandelt de bronnen om bij te dragen aan open source voor beginners op bas
```suggestion
- ["Aan de slag met Open Source" door Sayan Chowdhury](https://www.hackerearth.com:443/getstarted-opensource/) - Dit artikel behandelt de bronnen om bij te dragen aan open source voor beginners op basis van hun favoriete taalinteresse.
```

2021-03-26 08:50 UTC, noah-vdv commented on README-NL.md
> +- ["Blader door goede eerste nummers om bij te dragen aan open source"](https://github.blog/2020-01-22-browse-good-first-issues-to-start-contributing-to-open-source/) -GitHub helpt je nu bij het vind
```suggestion
- ["Blader door good first issues om bij te dragen aan open source"](https://github.blog/2020-01-22-browse-good-first-issues-to-start-contributing-to-open-source/) - GitHub helpt je nu bij het vinden van good first issues om bij te dragen aan open source.
```

2021-03-26 08:50 UTC, noah-vdv commented on README-NL.md
> +- [Git Best Practices](https://sethrobertson.github.io/GitBestPractices/) -Vaak vastleggen, later perfectioneren, een keer publiceren: Git Best Practices.
```suggestion
- [Denk als (een) Git](http://think-like-a-git.net/) - Git introductie voor "gevorderde beginners", maar worstelen nog steeds, om je een eenvoudige strategie te geven om veilig met git te experimenteren.
- [Probeer Git](https://try.github.io/) - Leer Git gratis in 15 minuten vanuit je browser.
- [Elke dag Git](https://git-scm.com/docs/giteveryday) - Een nuttige minimale set commando's voor elke dag gebruik van Git.
- [Oh shit, git!](https://ohshitgit.com/) - hoe je uit veelvoorkomende `git`-fouten kunt komen die in gewoon Engels worden beschreven; zie ook [Dangit, git!](https://dangitgit.com/) voor de pagina zonder vloeken.
- [Atlassian Git Tutorials](https://www.atlassian.com/git/tutorials) - verschillende tutorials over het gebruik van`git`.
- [GitHub Git Cheat Sheet](https://education.github.com/git-cheat-sheet-education.pdf) (PDF)
- [freeCodeCamp's Wiki op Git-bronnen](https://forum.freecodecamp.org/t/wiki-git-resources/13136)
- [GitHub Flow](https://www.youtube.com/watch?v=juLIxo42A_s) (42:06) - GitHub gesprek over het maken van een pull request.
- [GitHub Learning Resources](https://docs.github.com/en/github/getting-started-with-github/git-and-github-learning-resources) - Leermiddelen voor Git en GitHub.
- [Pro Git](https://git-scm.com/book/en/v2) - Het volledige Pro Git-boek, geschreven door Scott Chacon en Ben Straub en uitgegeven door Apress.
- [Git-it](https://github.com/jlord/git-it-electron) - Stap voor stap Git tutorial desktop-app.
- [Vliegregels voor Git](https://github.com/k88hudson/git-flight-rules) - Een gids over wat u moet doen als er iets misgaat.
- [Git-gids voor beginners in het Spaans](https://platzi.github.io/git-slides/#/) - Een complete gids met dia's over git en GitHub uitgelegd in het Spaans.
- [Git Kraken](https://www.gitkraken.com/git-client) - Visueel, platformonafhankelijk en interactief `git` desktop applicatie voor versiebeheer.
- [Git-tips](https://github.com/git-tips/tips) - Verzameling van de meest gebruikte git tips en trucs.
- [Git Best Practices](https://sethrobertson.github.io/GitBestPractices/) - Vaak vastleggen, later perfectioneren, een keer publiceren: Git Best Practices.
```

2021-03-26 08:50 UTC, noah-vdv commented on README-NL.md
> +- [Open bronnen: stemmen uit de open source-revolutie](https://www.oreilly.com/openbook/opensources/book/) -Essays van open-sourcepioniers zoals Linus Torvalds (Linux), Larry Wall (Perl) en Richard S
```suggestion
- [Open Sources: stemmen uit de open source-revolutie](https://www.oreilly.com/openbook/opensources/book/) - Essays van open-sourcepioniers zoals Linus Torvalds (Linux), Larry Wall (Perl) en Richard Stallman (GNU).
```

2021-03-26 08:50 UTC, noah-vdv commented on README-NL.md
> +- [Ovio](https://ovio.org) -Een platform met een samengestelde selectie van bijdragervriendelijke projecten. Het heeft een [krachtige tool voor het zoeken naar problemen] (https://ovio.org/issues) wa
```suggestion
- [Voor het oprapen](https://up-for-grabs.net/) - Bevat projecten met beginnersvriendelijke problemen.
- [First timers only](https://www.firsttimersonly.com/) - Een lijst met bugs die zijn gelabeld "first timers only".
- [Eerste bijdragen](https://firstcontributions.github.io/) - Lever uw eerste Open Source-bijdrage in 5 minuten. Een tool en tutorial om beginners op weg te helpen met bijdragen. [Hier](https://github.com/firstcontributions/first-contributions) is de GitHub-broncode voor de site en de mogelijkheid om een ​​bijdrage te leveren aan de repository zelf.
- [Hacktoberfest](https://hacktoberfest.digitalocean.com/) - Een programma om Open Source-bijdragen aan te moedigen. Verdien cadeaus zoals t-shirts en stickers door ten minste vier pull requests in de maand oktober te doen.
- [24 Pull Requests](https://24pullrequests.com) - 24 Pull Requests is een project om Open Source samenwerking in de maand december te promoten.
- [Ovio](https://ovio.org) - Een platform met een samengestelde selectie van bijdragervriendelijke projecten. Het heeft een [krachtige tool voor het zoeken naar issues](https://ovio.org/issues) waarmee u projecten en problemen kunt opslaan voor later.
```

2021-03-26 09:37 UTC, noah-vdv reviewed
Small fix

2021-03-26 09:37 UTC, noah-vdv commented on README-NL.md
>  ## Het bijdragende ecosysteem van Mozilla**
```suggestion
## Het bijdragende ecosysteem van Mozilla
```

2021-03-26 09:37 UTC, noah-vdv commented on README-NL.md
>  ## Versie control gebruiken**
```suggestion
## Versie control gebruiken
```

2021-03-26 09:37 UTC, noah-vdv commented on README-NL.md
>  ## Open Source boeken**
```suggestion
## Open Source boeken
```

2021-03-26 09:37 UTC, noah-vdv commented on README-NL.md
> +## Open Source bijdrage-initiatieven**
```suggestion
## Open Source bijdrage-initiatieven
```

2021-03-26 09:41 UTC, noah-vdv commented on README-NL.md
> +- [Start Mozilla](https://twitter.com/StartMozilla) - a Twitter account that tweets about issues fit for contributors new to the Mozilla ecosystem.
```suggestion
- [Good first bug](https://bugzil.la/sw:%22[good%20first%20bug]%22&limit=0) - bugs die ontwikkelaars hebben geïdentificeerd als een goede introductie tot het project.
- [Mentored Bugs](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=mentor%3A%40) - bugs waaraan een mentor is toegewezen die aanwezig zal zijn op IRC om je te helpen als je vastloopt tijdens het werken aan een oplossing.
- [Bugs Ahoy](https://www.joshmatthews.net/bugsahoy/) -een site gewijd aan het vinden van bugs op Bugzilla.
- [Firefox DevTools](http://firefox-dev.tools/) - een site gewijd aan bugs die zijn ingediend voor de ontwikkelaarstools in de Firefox-browser.
- [Wat kan ik doen voor Mozilla](https://whatcanidoformozilla.org/) - Zoek uit waar je aan kunt werken door een aantal vragen over je vaardigheden en interesses te beantwoorden.
- [Start Mozilla](https://twitter.com/StartMozilla) - een Twitter-account dat tweets plaatst over kwesties die geschikt zijn voor bijdragers die nieuw zijn in het Mozilla-ecosysteem.
```

2021-04-01 18:38 UTC, erictleung commented
> 
> 
> Mostly a couple of nitpicks.
> Also, probably a question for @erictleung : Should titles of articles, sites, etc. be translated or not?

I don't mind either. But for simplicity, we can leave them alone for now unless someone wants to translate those as well.

2021-05-16 18:35 UTC, Lorretje approved these changes

2022-01-04 18:33 UTC, closed without merging