add arabic language
freeCodeCamp/how-to-contribute-to-open-source pull request #670
Opened 2022-03-11 15:57 UTC by obeidahr

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-03-30 10:52 UTC, Salloom99 approved these changes
I've read the translation from English to Arabic and it seems accurate to me.

2022-04-06 06:57 UTC, erictleung requested changes
Thanks for making time to translate this! Just one quick update to the table of contents and then I can merge it. Thanks!

2022-04-06 06:57 UTC, erictleung commented on README-AR.md
> +- [License](#license)
Please update these to match your changes.

```suggestion
- [Contributing to Open Source in general](#المساهمة-في-المصادر-المفتوحة-بشكل-عام)
- [Direct GitHub searches](#عمليات-البحث-المباشرة-على-github)
- [Mozilla's contributor ecosystem](#النظام-البيئي-للمساهمين-في-mozilla)
- [Useful articles for new Open Source contributors](#مقالات-مفيدة-للمساهمين-الجدد-في-المصادر-المفتوحة)
- [Using Version Control](#باستخدام-التحكم-في-الإصدار)
- [Open Source books](#كتب-مفتوحة-المصدر)
- [Open Source contribution initiatives](#مبادرات-مساهمة-المصدر-المفتوح)
- [Open Source programs to participate in](#برامج-مفتوحة-المصدر-للمشاركة-فيها)
- [License](#license)
```

2022-04-06 19:16 UTC, erictleung approved these changes
LGTM! Thanks for taking the time to make this translation ✨

2022-04-06 19:19 UTC, merged