docs: remove grammatical errors & fix links in README of Hindi language
freeCodeCamp/how-to-contribute-to-open-source pull request #799
Opened 2022-10-04 05:35 UTC by Rahulbaran

- Fixed markdown errors for links
- Removed some hindi grammatical errors

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.

Closes #XXXXX

2022-10-04 20:30 UTC, erictleung requested changes

2022-10-05 01:30 UTC, Rahulbaran commented on README-HI.md
> +- [ओपन सोर्स पुस्तकें](#open-source-books)
I will fix that and make a PR

2022-10-05 01:49 UTC, Rahulbaran commented
Changes made in lines 125,127,129 & 135

2022-10-14 12:59 UTC, Rahulbaran commented
Someone please check my PR

2022-11-05 14:23 UTC, erictleung reviewed
LGTM! 👍 Thanks for your patience. We appreciate your grammatical review and suggestions for our translations ✨

2022-11-05 14:23 UTC, erictleung approved these changes

2022-11-05 14:23 UTC, merged